# Base configuration
new_baseurl: "http://127.0.0.1:4000/"  # Base URL configuration
url: "https://ivanweissvanderpolgh.github.io/"
certifications_path: "assets/img/Certifications/"

# Site Information
title: "Ivan Weiss Van Der Pol - Portfolio"
description: "A Github Pages (Jekyll) template based on TailwindCSS"
theme-color: "green" # Options: indigo, yellow, pink, green, stone

# Quoting strings that include special characters
author: "Ivan Weiss Van Der Pol"
author-bio: "Passionate Software Engineer Specializing in QA Automation"
author-image: "/assets/img/logos/logo_face.png"

# Social Media Links - Ensure URLs are in quotes
instagram: "https://www.instagram.com/ivan_weiss_van_der_pol/"
github: "https://github.com/IvanWeissVanDerPolGH/"
linkedin: "https://www.linkedin.com/in/ivanweissvanderpol/"

# Collections Configuration
collections:
  Pages_content:
    output: true
    permalink: /:collection/:name/
    permalink: /certification-listed/:name/

# Navigation menu
show-nav-menu: true
nav-menu:
  - text: "About Me"
    permalink: "about-me"
  - text: "Education"
    permalink: "education"
  - text: "Certifications"
    permalink: "certifications"
  - text: "Work Experience"
    permalink: "work_experience"
  - text: "Projects"
    permalink: "projects"
  - text: "Travels"
    permalink: "travels"

# Social media links
twitter: false
facebook: false
instagram: "https://www.instagram.com/ivan_weiss_van_der_pol/"
github: "https://github.com/IvanWeissVanDerPolGH/"
linkedin: "https://www.linkedin.com/in/ivanweissvanderpol/"
medium: false
google-scholar: false
phone_number: "+595981324569"
email: "weissvanderpol.ivan@gmail.com"
# Footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: "https://github.com/harrywang/tailpages"

# Google Analytics
google-analytics: "G-WCRC1TC2V5"

# Jekyll plugins
plugins:
  - jekyll-seo-tag

# Collections
collections:
  Pages_content:
    output: true
    permalink: /:name/

# Files and folders to exclude from the build
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "node_modules"
  - "README.md"
  - "LICENSE"
  - "yarn.lock"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "test/"

palette: "palette-classic-blue"
