# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://ivanweissvanderpolgh.github.io/" # the url of your github pages

# site information used in page title, meta data etc.
title: "Ivan Weiss Van Der Pol - Portfolio"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Ivan Weiss Van Der Pol
author-bio: Creator of Bitcoin  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: https://www.instagram.com/ivan_weiss_van_der_pol/
github: https://github.com/IvanWeissVanDerPolGH/
linkedin: https://www.linkedin.com/in/ivanweissvanderpol/
medium: false
google-scholar: false
email: weissvanderpol.ivan@gmail.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
